name: Build Astral Quest

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: devkitpro/devkitarm:latest
    defaults:
      run:
        working-directory: .github/workflows   # <— build exactly where your files are
    steps:
      - uses: actions/checkout@v4

      - name: Show files (debug)
        run: |
          pwd
          ls -la

      - name: Build
        run: make

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: astral_quest_build
          path: |
            .github/workflows/astral_quest.nds
            .github/workflows/*.map
            .github/workflows/*.elf
