name: Build NDS
on:
  push:
    branches: [ "**" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: devkitpro/devkitarm:latest
    steps:
      - uses: actions/checkout@v4
      - name: Initialize pacman keys
        run: |
          pacman-key --init
          pacman-key --populate
      - name: Sync pacman database
        run: dkp-pacman -Syu --noconfirm
      - name: Install nds-dev and tools
        run: dkp-pacman -S --noconfirm devkitARM general-tools dstools ndstool libnds libfat-nds nds-dev dkp-toolchain-vars
      - name: Set up devkitPro environment
        run: source /etc/profile.d/devkit-env.sh
      - name: Build .NDS
        run: make
      - name: Upload NDS artifact
        uses: actions/upload-artifact@v4
        with:
          name: astral_quest_build
          path: |
            astral_quest.nds
            *.map
            *.elf
