name: Build Astral Quest
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: devkitpro/devkitarm:latest
    steps:
      - uses: actions/checkout@v4

      # Install missing Calico package so calico.h is available
      - name: Install Calico headers
        run: |
          dkp-pacman -Sy --noconfirm calico

      - name: Build
        run: make

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: astral_quest_build
          path: |
            astral_quest.nds
            *.map
            *.elf
