name: Build NDS
on:
  push:
    branches: [ "**" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: devkitpro/devkitarm:latest
    steps:
      - uses: actions/checkout@v4
      - name: Initialize pacman keys
        run: |
          pacman-key --init
          pacman-key --populate
      - name: Add fallback pacman mirror and sync database
        run: |
          echo "Server = https://apt.devkitpro.org/packages/\$repo" > /etc/pacman.d/mirrorlist
          dkp-pacman -Syyu --noconfirm
      - name: Install full nds development tools
        run: dkp-pacman -S --noconfirm devkitARM general-tools dstools ndstool libnds libfat-nds nds-dev devkitARM-rules dkp-toolchain-vars
      - name: Build .NDS with verbose output
        shell: bash
        run: |
          source /opt/devkitpro/devkit-env.sh
          make V=1
      - name: Upload NDS artifact
        uses: actions/upload-artifact@v4
        with:
          name: astral_quest_build
          path: |
            astral_quest.nds
            *.map
            *.elf
