name: Build Astral Quest
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: devkitpro/devkitarm:20240706   # ✅ pre-Calico libnds, no calico.h issues
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: make
      - name: Upload Artifact
        uses: actions/upload-art
