name: Build NDS
on:
  push:
    branches: [ "**" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: devkitpro/devkitarm:latest
    steps:
      - uses: actions/checkout@v4
      - name: Build .NDS
        run: make
      - name: Upload NDS artifact
        uses: actions/upload-artifact@v4
        with:
          name: astral_quest_build
          path: |
            astral_quest.nds
            *.map
            *.elf
